# Generated by Django 2.1.7 on 2019-03-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
    migrations.CreateModel(
    name='AllGames',
    fields=[
    ('match_date', models.CharField(max_length=40)),
    ('time', models.CharField(max_length=40)),
    ('teams', models.CharField(max_length=400, primary_key=True, serialize=False)),
    ('tip', models.CharField(max_length=10)),
    ('tip_odd', models.CharField(default='0.00', max_length=10)),
    ('ft_results', models.CharField(max_length=40)),
    ('outcome_text', models.CharField(max_length=40)),
    ],
    ),
    migrations.CreateModel(
    name='Featured',
    fields=[
    ('match_date', models.CharField(max_length=40)),
    ('time', models.CharField(max_length=40)),
    ('teams', models.CharField(max_length=400, primary_key=True, serialize=False)),
    ('tip', models.CharField(max_length=10)),
    ('tip_odd', models.CharField(default='0.00', max_length=10)),
    ('ft_results', models.CharField(max_length=40)),
    ('outcome_text', models.CharField(max_length=40)),
    ],
    ),
    migrations.CreateModel(
    name='Over15',
    fields=[
    ('match_date', models.CharField(max_length=40)),
    ('time', models.CharField(max_length=40)),
    ('teams', models.CharField(max_length=400, primary_key=True, serialize=False)),
    ('tip_ov', models.CharField(max_length=10)),
    ('tip_ov_odd', models.CharField(default='0.00', max_length=10)),
    ('ft_results', models.CharField(max_length=40)),
    ('outcome_text', models.CharField(max_length=40)),
    ],
    ),
    migrations.CreateModel(
    name='Over25',
    fields=[
    ('match_date', models.CharField(max_length=40)),
    ('time', models.CharField(max_length=40)),
    ('teams', models.CharField(max_length=400, primary_key=True, serialize=False)),
    ('tip_ov', models.CharField(max_length=10)),
    ('tip_ov_odd', models.CharField(default='0.00', max_length=10)),
    ('ft_results', models.CharField(max_length=40)),
    ('outcome_text', models.CharField(max_length=40)),
    ],
    ),
    migrations.CreateModel(
    name='Over35',
    fields=[
    ('match_date', models.CharField(max_length=40)),
    ('time', models.CharField(max_length=40)),
    ('teams', models.CharField(max_length=400, primary_key=True, serialize=False)),
    ('tip_ov', models.CharField(max_length=10)),
    ('tip_ov_odd', models.CharField(default='0.00', max_length=10)),
    ('ft_results', models.CharField(max_length=40)),
    ('outcome_text', models.CharField(max_length=40)),
    ],
    ),
    migrations.CreateModel(
    name='TipGG',
    fields=[
    ('match_date', models.CharField(max_length=40)),
    ('time', models.CharField(max_length=40)),
    ('teams', models.CharField(max_length=400, primary_key=True, serialize=False)),
    ('tip_gg', models.BooleanField(default=False)),
    ('tip_gg_odd', models.CharField(default='0.00', max_length=10)),
    ('ft_results', models.CharField(max_length=40)),
    ('outcome_text', models.CharField(max_length=40)),
    ],
    ),
    ]
