# Generated by Django 2.1.7 on 2019-03-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllGames',
            fields=[
                ('match_date', models.CharField(max_length=40)),
                ('time', models.CharField(max_length=40)),
                ('teams', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('tip', models.CharField(max_length=40)),
                ('tip_odd', models.CharField(default='0.00', max_length=5)),
                ('tipGG', models.BooleanField(default=False)),
                ('tipGG_odd', models.CharField(default='0.00', max_length=5)),
                ('tipOv', models.CharField(default='2.5', max_length=5)),
                ('tipOV_odd', models.CharField(default='0.00', max_length=5)),
                ('ft_results', models.CharField(max_length=40)),
                ('outcome_text', models.CharField(max_length=40)),
            ],
        ),
    ]
