# Generated by Django 2.1.7 on 2019-03-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal_goal',
            name='team',
        ),
        migrations.AddField(
            model_name='allgames',
            name='tipGG',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='allgames',
            name='tipGG_odd',
            field=models.CharField(default='0.00', max_length=5),
        ),
        migrations.AddField(
            model_name='allgames',
            name='tipOV_odd',
            field=models.CharField(default='0.00', max_length=5),
        ),
        migrations.AddField(
            model_name='allgames',
            name='tipOv',
            field=models.CharField(default='2.5', max_length=5),
        ),
        migrations.AlterField(
            model_name='allgames',
            name='tip_odd',
            field=models.CharField(default='0.00', max_length=5),
        ),
        migrations.DeleteModel(
            name='goal_Goal',
        ),
    ]
