# Generated by Django 2.1.7 on 2019-03-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipgg',
            name='tip_gg',
            field=models.CharField(max_length=10),
        ),
    ]
