# Generated by Django 2.1.7 on 2019-02-23 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_zulubet_result_overall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zulubet',
            old_name='overall_result',
            new_name='outcome_text',
        ),
    ]
