# Generated by Django 2.1.7 on 2019-03-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190310_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured',
            fields=[
                ('match_date', models.CharField(max_length=40)),
                ('time', models.CharField(max_length=40)),
                ('teams', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('tip', models.CharField(max_length=40)),
                ('tip_odd', models.CharField(default='0.00', max_length=10)),
                ('ft_results', models.CharField(max_length=40)),
                ('outcome_text', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='allgames',
            name='outcome_text',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='allgames',
            name='tip_odd',
            field=models.CharField(default='0.00', max_length=10),
        ),
    ]
