# Generated by Django 2.1.7 on 2019-03-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190312_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Over15',
            fields=[
                ('match_date', models.CharField(max_length=40)),
                ('time', models.CharField(max_length=40)),
                ('teams', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('tipOv', models.BooleanField(default=False)),
                ('tipOV_odd', models.CharField(default='0.00', max_length=10)),
                ('ft_results', models.CharField(max_length=40)),
                ('outcome_text', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Over25',
            fields=[
                ('match_date', models.CharField(max_length=40)),
                ('time', models.CharField(max_length=40)),
                ('teams', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('tipOv', models.BooleanField(default=False)),
                ('tipOV_odd', models.CharField(default='0.00', max_length=10)),
                ('ft_results', models.CharField(max_length=40)),
                ('outcome_text', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Over35',
            fields=[
                ('match_date', models.CharField(max_length=40)),
                ('time', models.CharField(max_length=40)),
                ('teams', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('tipOv', models.BooleanField(default=False)),
                ('tipOV_odd', models.CharField(default='0.00', max_length=10)),
                ('ft_results', models.CharField(max_length=40)),
                ('outcome_text', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='TipGG',
            fields=[
                ('match_date', models.CharField(max_length=40)),
                ('time', models.CharField(max_length=40)),
                ('teams', models.CharField(max_length=400, primary_key=True, serialize=False)),
                ('tipGG', models.BooleanField(default=False)),
                ('tipGG_odd', models.CharField(default='0.00', max_length=10)),
                ('ft_results', models.CharField(max_length=40)),
                ('outcome_text', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='allgames',
            name='tipGG',
        ),
        migrations.RemoveField(
            model_name='allgames',
            name='tipGG_odd',
        ),
        migrations.RemoveField(
            model_name='allgames',
            name='tipOV_odd',
        ),
        migrations.RemoveField(
            model_name='allgames',
            name='tipOv',
        ),
    ]
