# Generated by Django 2.1.7 on 2019-03-16 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190316_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='over15',
            old_name='tipOv',
            new_name='tip_ov',
        ),
        migrations.RenameField(
            model_name='over15',
            old_name='tipOV_odd',
            new_name='tip_ov_odd',
        ),
        migrations.RenameField(
            model_name='over25',
            old_name='tipOv',
            new_name='tip_ov',
        ),
        migrations.RenameField(
            model_name='over25',
            old_name='tipOV_odd',
            new_name='tip_ov_odd',
        ),
        migrations.RenameField(
            model_name='over35',
            old_name='tipOv',
            new_name='tip_ov',
        ),
        migrations.RenameField(
            model_name='over35',
            old_name='tipOV_odd',
            new_name='tip_ov_odd',
        ),
        migrations.RenameField(
            model_name='tipgg',
            old_name='tipGG',
            new_name='tip_gg',
        ),
        migrations.RenameField(
            model_name='tipgg',
            old_name='tipGG_odd',
            new_name='tipgg_odd',
        ),
    ]
