# Generated by Django 2.1.7 on 2019-03-16 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190316_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipgg',
            old_name='tipgg_odd',
            new_name='tip_gg_odd',
        ),
    ]
