# Generated by Django 2.1.7 on 2019-03-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190316_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allgames',
            name='tip',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='featured',
            name='tip',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='over15',
            name='tip_ov',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='over25',
            name='tip_ov',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='over35',
            name='tip_ov',
            field=models.CharField(max_length=10),
        ),
    ]
